CREATE TABLE [DIM_CANDIDATOS] (
  [SQ_CANDIDATOS] int PRIMARY KEY,
  [NM_CANDIDATO] nvarchar(255),
  [NR_PARTIDO] int,
  [NM_PARTIDO] nvarchar(255),
  [NR_TURNO] int,
  [ANO] int NOT NULL
)
GO

CREATE TABLE [DIM_LOCALVOTACAO] (
  [NR_SECAO] INT,
  [DS_ENDERECO_LOCVT_ORIGINAL] nvarchar(255),
  [NM_MUNICIPIO] nvarchar(255),
  [NR_CEP] INT,
  [DS_ENDERECO] nvarchar(255),
  [NR_ZONA] INT,
  [NM_BAIRRO] nvarchar(255),
  [ANO] INT NOT NULL,
  PRIMARY KEY ([NR_SECAO], [DS_ENDERECO_LOCVT_ORIGINAL], [NM_MUNICIPIO], [NR_CEP])
)
GO

CREATE TABLE [DIM_POSICAOGEOGRAFICA] (
  [NR_LOCAL_VOTACAO_ORIGINAL] INT PRIMARY KEY,
  [ANO] INT NOT NULL,
  [NR_LATITUDE] float,
  [NR_LONGITUDE] float
)
GO

CREATE TABLE [FATO_VOTOS] (
  [SQ_CANDIDATO] int,
  [NR_SECCAO] int,
  [NM_LOCAL_VOTACAO] VARCHAR,
  [QT_APTOS] INT,
  [QT_COMPARECIMENTO] INT,
  [QT_ABSTENCOES] INT,
  [QT_VOTOS_NOMINAIS] INT,
  [QT_VOTOS_BRANCOS] INT,
  [QT_VOTOS_NULOS] INT,
  [QT_VOTOS_LEGENDA] INT,
  [QT_VOTOS_ANULADOS_APU_SEP] INT,
  [ANO] INT NOT NULL,
  [CD_FAIXA_ETARIA] INT NOT NULL,
  [DS_FAIXA_ETARIA] VARCHAR NOT NULL,
  PRIMARY KEY ([SQ_CANDIDATO], [NR_SECCAO], [NM_LOCAL_VOTACAO])
)
GO

CREATE TABLE [DIM_IDHMPROX] (
  [SK_ID] INT PRIMARY KEY,
  [NM_MUNICIPIO] nvarchar(255) NOT NULL,
  [ANO] INT NOT NULL,
  [PIB] float,
  [IDEB_CONSOLIDADO] float,
  [COBERTURA_AGUA_POTAVEL] float
)
GO

CREATE TABLE [DIM_CALENDARIO] (
  [ANO] INT,
  [DIA] INT,
  PRIMARY KEY ([DIA], [ANO])
)
GO

CREATE TABLE [DIM_QTDE_CHUVA] (
  [ANO] int,
  [DIA] int,
  [HORA] int,
  [PRECIPITAÇÃO_TOTAL_HORA] float,
  [UMIDADE_RELATIVA_AR] FLOAT,
  PRIMARY KEY ([HORA], [DIA], [ANO])
)
GO

EXEC sp_addextendedproperty
@name = N'Column_Description',
@value = 'Chave Primária Surrogate / Negócio',
@level0type = N'Schema', @level0name = 'dbo',
@level1type = N'Table',  @level1name = 'DIM_CANDIDATOS',
@level2type = N'Column', @level2name = 'SQ_CANDIDATOS';
GO

EXEC sp_addextendedproperty
@name = N'Column_Description',
@value = 'FK para DIM_CANDIDATOS',
@level0type = N'Schema', @level0name = 'dbo',
@level1type = N'Table',  @level1name = 'FATO_VOTOS',
@level2type = N'Column', @level2name = 'SQ_CANDIDATO';
GO

EXEC sp_addextendedproperty
@name = N'Column_Description',
@value = 'FK para DIM_LOCALVOTACAO',
@level0type = N'Schema', @level0name = 'dbo',
@level1type = N'Table',  @level1name = 'FATO_VOTOS',
@level2type = N'Column', @level2name = 'NR_SECCAO';
GO

ALTER TABLE [DIM_CANDIDATOS] ADD FOREIGN KEY ([SQ_CANDIDATOS]) REFERENCES [FATO_VOTOS] ([SQ_CANDIDATO])
GO

ALTER TABLE [DIM_LOCALVOTACAO] ADD FOREIGN KEY ([NR_SECAO]) REFERENCES [FATO_VOTOS] ([NR_SECCAO])
GO

ALTER TABLE [DIM_LOCALVOTACAO] ADD FOREIGN KEY ([DS_ENDERECO_LOCVT_ORIGINAL]) REFERENCES [FATO_VOTOS] ([NM_LOCAL_VOTACAO])
GO

ALTER TABLE [FATO_VOTOS] ADD FOREIGN KEY ([ANO]) REFERENCES [DIM_CALENDARIO] ([ANO])
GO

ALTER TABLE [DIM_POSICAOGEOGRAFICA] ADD FOREIGN KEY ([NR_LOCAL_VOTACAO_ORIGINAL]) REFERENCES [DIM_LOCALVOTACAO] ([NR_SECAO])
GO

ALTER TABLE [DIM_LOCALVOTACAO] ADD FOREIGN KEY ([ANO]) REFERENCES [DIM_CALENDARIO] ([ANO])
GO

ALTER TABLE [DIM_CANDIDATOS] ADD FOREIGN KEY ([ANO]) REFERENCES [DIM_CALENDARIO] ([ANO])
GO

ALTER TABLE [DIM_IDHMPROX] ADD FOREIGN KEY ([NM_MUNICIPIO]) REFERENCES [DIM_LOCALVOTACAO] ([NM_MUNICIPIO])
GO

ALTER TABLE [DIM_IDHMPROX] ADD FOREIGN KEY ([ANO]) REFERENCES [DIM_CALENDARIO] ([ANO])
GO

ALTER TABLE [DIM_QTDE_CHUVA] ADD FOREIGN KEY ([ANO]) REFERENCES [DIM_CALENDARIO] ([ANO])
GO

ALTER TABLE [DIM_QTDE_CHUVA] ADD FOREIGN KEY ([DIA]) REFERENCES [DIM_CALENDARIO] ([DIA])
GO
