// ==========================================
// DIMENSÕES
// ==========================================

Table DIM_CANDIDATOS {
  SQ_CANDIDATOS int [pk, note: 'Chave Primária Surrogate / Negócio']
  NM_CANDIDATO varchar
  NR_PARTIDO int
  NM_PARTIDO varchar
  NR_TURNO int
  ANO_ELEICAO int
}

Table eleitorado_local_votacao {
  NR_SECAO INT [PK] 
  SK_SECAO INT [PK] 
  DS_ENDERECO varchar
  NR_ZONA INT
  NM_BAIRRO VARCHAR
  CD_MUNICIPIO INT
  NM_MUNICIPIO varchar
  NR_CEP INT
  IDHPROX_MUNICIPIO float
  ANO_ELEICAO int
  NR_LATITUDE FLOAT
  NR_LONGITUDE FLOAT
}

Table DIM_LOCALVOTACAO {
  SK_SECAO int [pk, note: 'Chave Primária Surrogate']
  LOCAL_VOTACAO varchar
  REGIAO varchar
  LOCAL varchar
  MUNICIPIO varchar
  IDHM_MUNICIPIO float
  TIPOLOCAL varchar [note: 'Ex: PERIFERIA, CENTRO']
  ANO_ELEICAO int
}

Table DIM_POSICAOGEOGRAFICA {
  ID_POSICAO int [pk]
  LOCAL_VOTACAO varchar
  ANO int
  LATITUDE float
  LONGITUDE float
  SOFREU_CHUVA boolean
  ANO_ELEICAO int
}

// ==========================================
// FATOS / TABELAS DE MEDIDAS
// ==========================================

Table eleitorado_secao {
  NR_SECAO INT [PK]
  SK_SECAO INT [PK]
}

Table detalhes_votacao_secao {
  NR_SECAO INT [PK]
  QT_APTOS INT
  QT_COMPARECIMENTO INT
  QT_ABSTENCOES INT
  QT_VOTOS_NOMINAIS INT
  QT_VOTOS_BRANCOS INT
  QT_VOTOS_NULOS INT
  QT_VOTOS_LEGENDA INT
  QT_VOTOS_ANULADOS_APU_SEP INT
}

Table perfil_eleitor_secao {
  ANO INT [PK]
  CD_FAIXA_ETARIA INT
  DS_FAIXA_ETARIA VARCHAR
  NR_SECAO INT
}

Table FATO_VOTOS {
  SQ_CANDIDATO int [note: 'FK para DIM_CANDIDATOS']
  SK_SECAO int [note: 'FK para DIM_LOCALVOTACAO']
  VOTOS_PORSESSAO_nominal int
  VOTOS_NULOS_E_BRANCOS_PORSESSAO int
  VOTOS_FAIXAETARIA_PORSESSAO int
  VOTOS_PORCANDIDATO_PORSESSAO int
  ANO_ELEICAO int
}


// ==========================================
// RELACIONAMENTOS (Star Schema - N:1 / Fato > Dimensão)
// ==========================================

// Ligação da Fato Principal com as Dimensões
Ref: FATO_VOTOS.SQ_CANDIDATO > DIM_CANDIDATOS.SQ_CANDIDATOS
Ref: FATO_VOTOS.SK_SECAO > DIM_LOCALVOTACAO.SK_SECAO

// Ligação dos agregados de Seção à Dimensão de Local de Votação
Ref: detalhes_votacao_secao.NR_SECAO > DIM_LOCALVOTACAO.SK_SECAO
Ref: perfil_eleitor_secao.NR_SECAO > DIM_LOCALVOTACAO.SK_SECAO
Ref: eleitorado_secao.SK_SECAO > DIM_LOCALVOTACAO.SK_SECAO
Ref: eleitorado_local_votacao.SK_SECAO > DIM_LOCALVOTACAO.SK_SECAO

// Ligação de Posição Geográfica à Dimensão de Local
Ref: DIM_POSICAOGEOGRAFICA.ID_POSICAO < DIM_LOCALVOTACAO.SK_SECAO